language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
    - python-pykickstart
script: shellcheck -e SC2086 -s bash create-image create-iso sdc-vmmanifest setup_env.sh
script: ksvalidator --firsterror ks.cfg
